name: "Auto-Streak Keeper"
description: "Maintains GitHub streak by creating and updating a file daily."
author: "priyank sutariya"
inputs:
  file-path:
    description: "Path to the file to create/update"
    required: false
    default: "public/auto-streak/data.txt"
  min-commits:
    description: "Minimum number of commits daily"
    required: false
    default: 1
  max-commits:
    description: "Maximum number of commits daily"
    required: false
    default: 15
  commit-message:
    description: "Commit message for the update"
    required: false
    default: "Auto-streak update"
  user-name:
    description: "User name for the commit"
    required: true
  user-email:
    description: "User email for the commit"
    required: true
  github-token:
    description: "GitHub token for authentication"
    required: true
  branch-name:
    description: "Branch name to push the updates"
    required: false
    default: "auto-streak-keeper"

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: 'git-pull-request'
  color: 'gray-dark'
