name: Maintain GitHub Streak

on:
 schedule:
   - cron: "0 0 * * *" # Runs daily at midnight
 workflow_dispatch:

jobs:
 auto-streak:
   runs-on: ubuntu-latest
   permissions:
     contents: write

   steps:
     - name: Checkout Repository
       uses: actions/checkout@v3

     - name: Set up Node.js
       uses: actions/setup-node@v3
       with:
         node-version: "20"

     - name: Run Auto-Streak Keeper
       uses: bmiit145/auto-streak-keeper@v1.0.1
       with:
         file-path: "public/auto-streak/data.txt"
         min-commits: 2
         max-commits: 5
         commit-message: "Daily streak maintenance"
         user-name: ${{ secrets.GITHUB_USER_NAME }}
         user-email: ${{ secrets.GITHUB_USER_EMAIL }}
         github-token: ${{ secrets.GITHUB_TOKEN }}
