name: Test Auto-Streak Keeper

on:
  push:
  workflow_dispatch:

jobs:
  test-auto-streak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Auto-Streak Keeper
        uses: ./ # Use the current repository
        with:
          file-path: "public/auto-streak/data.txt"
          min-commits: 3
          max-commits: 10
          commit-message: "Testing Auto-Streak Keeper"
