name: Auto-Streak Keeper

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:

jobs:
  auto-streak:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Run the Local Action
      - name: Run Auto-Streak Keeper
        uses: bmiit145/auto-streak-keeper@v1.0.0
        with:
          file-path: "public/auto-streak/data.txt"
          min-commits: 3
          max-commits: 10
          commit-message: "Daily streak maintenance"
